# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1f70dfa2c97edf5dceb4b251f9ae79c"
name = "Overall"
application_url = "https://youth-diego-development-items.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nexus-booster.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://youth-diego-development-items.trycloudflare.com/auth/callback",
  "https://youth-diego-development-items.trycloudflare.com/auth/shopify/callback",
  "https://youth-diego-development-items.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
