--------------------------  Countries -------------------------------

INSERT INTO "Country" ("id", "name")
VALUES ('AF', 'Afghanistan'),
       ('AL', 'Albania'),
       ('BQ', 'Bonaire'),
       ('BL', 'Saint Barthélemy'),
       ('SX', 'Sint Maarten'),
       ('CW', 'Curaçao'),
       ('MF', 'Marigot'),
       ('DZ', 'Algeria'),
       ('AS', 'American Samoa'),
       ('AD', 'Andorra'),
       ('AO', 'Angola'),
       ('AI', 'Anguilla'),
       ('AQ', 'Antarctica'),
       ('AG', 'Antigua and Barbuda'),
       ('AR', 'Argentina'),
       ('AM', 'Armenia'),
       ('AW', 'Aruba'),
       ('AU', 'Australia'),
       ('AT', 'Austria'),
       ('AZ', 'Azerbaijan'),
       ('BS', 'Bahamas'),
       ('BH', 'Bahrain'),
       ('BD', 'Bangladesh'),
       ('BB', 'Barbados'),
       ('BY', 'Belarus'),
       ('BE', 'Belgium'),
       ('BZ', 'Belize'),
       ('BJ', 'Benin'),
       ('BM', 'Bermuda'),
       ('BT', 'Bhutan'),
       ('BO', 'Bolivia'),
       ('BA', 'Bosnia and Herzegovina'),
       ('BW', 'Botswana'),
       ('BV', 'Bouvet Island'),
       ('AX', 'Åland Islands'),
       ('BR', 'Brazil'),
       ('IO', 'British Indian Ocean Territory'),
       ('BN', 'Brunei Darussalam'),
       ('BG', 'Bulgaria'),
       ('BF', 'Burkina Faso'),
       ('BI', 'Burundi'),
       ('KH', 'Cambodia'),
       ('CM', 'Cameroon'),
       ('CA', 'Canada'),
       ('CV', 'Cape Verde'),
       ('KY', 'Cayman Islands'),
       ('CF', 'Central African Republic'),
       ('TD', 'Chad'),
       ('CL', 'Chile'),
       ('CN', 'China'),
       ('CX', 'Christmas Island'),
       ('CC', 'Cocos (Keeling) Islands'),
       ('CO', 'Colombia'),
       ('KM', 'Comoros'),
       ('CD', 'Democratic Republic of the Congo'),
       ('CG', 'Republic of Congo'),
       ('CK', 'Cook Islands'),
       ('CR', 'Costa Rica'),
       ('HR', 'Croatia (Hrvatska)'),
       ('CU', 'Cuba'),
       ('CY', 'Cyprus'),
       ('CZ', 'Czech Republic'),
       ('DK', 'Denmark'),
       ('DJ', 'Djibouti'),
       ('DM', 'Dominica'),
       ('DO', 'Dominican Republic'),
       ('TL', 'East Timor'),
       ('EC', 'Ecuador'),
       ('EG', 'Egypt'),
       ('SV', 'El Salvador'),
       ('GQ', 'Equatorial Guinea'),
       ('ER', 'Eritrea'),
       ('EE', 'Estonia'),
       ('ET', 'Ethiopia'),
       ('FK', 'Falkland Islands (Malvinas)'),
       ('FO', 'Faroe Islands'),
       ('FJ', 'Fiji'),
       ('FI', 'Finland'),
       ('FR', 'France'),
       ('FX', 'France, Metropolitan'),
       ('GF', 'French Guiana'),
       ('PF', 'French Polynesia'),
       ('TF', 'French Southern Territories'),
       ('GA', 'Gabon'),
       ('GM', 'Gambia'),
       ('GE', 'Georgia'),
       ('DE', 'Germany'),
       ('GH', 'Ghana'),
       ('GI', 'Gibraltar'),
       ('GG', 'Guernsey'),
       ('GR', 'Greece'),
       ('GL', 'Greenland'),
       ('GD', 'Grenada'),
       ('GP', 'Guadeloupe'),
       ('GU', 'Guam'),
       ('GT', 'Guatemala'),
       ('GN', 'Guinea'),
       ('GW', 'Guinea-Bissau'),
       ('GY', 'Guyana'),
       ('HT', 'Haiti'),
       ('HM', 'Heard and Mc Donald Islands'),
       ('HN', 'Honduras'),
       ('HK', 'Hong Kong'),
       ('HU', 'Hungary'),
       ('IS', 'Iceland'),
       ('IN', 'India'),
       ('IM', 'Isle of Man'),
       ('ID', 'Indonesia'),
       ('IR', 'Iran (Islamic Republic of)'),
       ('IQ', 'Iraq'),
       ('IE', 'Ireland'),
       ('IL', 'Israel'),
       ('IT', 'Italy'),
       ('CI', 'Ivory Coast'),
       ('JE', 'Jersey'),
       ('JM', 'Jamaica'),
       ('JP', 'Japan'),
       ('JO', 'Jordan'),
       ('KZ', 'Kazakhstan'),
       ('KE', 'Kenya'),
       ('KI', 'Kiribati'),
       ('KP', 'Korea, Democratic People''s Republic of'),
       ('KR', 'Korea, Republic of'),
       ('XK', 'Kosovo'),
       ('KW', 'Kuwait'),
       ('KG', 'Kyrgyzstan'),
       ('LA', 'Lao People''s Democratic Republic'),
       ('LV', 'Latvia'),
       ('LB', 'Lebanon'),
       ('LS', 'Lesotho'),
       ('LR', 'Liberia'),
       ('LY', 'Libyan Arab Jamahiriya'),
       ('LI', 'Liechtenstein'),
       ('LT', 'Lithuania'),
       ('LU', 'Luxembourg'),
       ('MO', 'Macau'),
       ('MK', 'North Macedonia'),
       ('MG', 'Madagascar'),
       ('MW', 'Malawi'),
       ('MY', 'Malaysia'),
       ('MV', 'Maldives'),
       ('ML', 'Mali'),
       ('MT', 'Malta'),
       ('MH', 'Marshall Islands'),
       ('MQ', 'Martinique'),
       ('MR', 'Mauritania'),
       ('MU', 'Mauritius'),
       ('YT', 'Mayotte'),
       ('MX', 'Mexico'),
       ('FM', 'Micronesia, Federated States of'),
       ('MD', 'Moldova, Republic of'),
       ('MC', 'Monaco'),
       ('MN', 'Mongolia'),
       ('ME', 'Montenegro'),
       ('MS', 'Montserrat'),
       ('MA', 'Morocco'),
       ('MZ', 'Mozambique'),
       ('MM', 'Myanmar'),
       ('NA', 'Namibia'),
       ('NR', 'Nauru'),
       ('NP', 'Nepal'),
       ('NL', 'Netherlands'),
       ('AN', 'Netherlands Antilles'),
       ('NC', 'New Caledonia'),
       ('NZ', 'New Zealand'),
       ('NI', 'Nicaragua'),
       ('NE', 'Niger'),
       ('NG', 'Nigeria'),
       ('NU', 'Niue'),
       ('NF', 'Norfolk Island'),
       ('MP', 'Northern Mariana Islands'),
       ('NO', 'Norway'),
       ('OM', 'Oman'),
       ('PK', 'Pakistan'),
       ('PW', 'Palau'),
       ('PS', 'Palestine'),
       ('PA', 'Panama'),
       ('PG', 'Papua New Guinea'),
       ('PY', 'Paraguay'),
       ('PE', 'Peru'),
       ('PH', 'Philippines'),
       ('PN', 'Pitcairn'),
       ('PL', 'Poland'),
       ('PT', 'Portugal'),
       ('PR', 'Puerto Rico'),
       ('QA', 'Qatar'),
       ('RE', 'Reunion'),
       ('RO', 'Romania'),
       ('RU', 'Russian Federation'),
       ('RW', 'Rwanda'),
       ('KN', 'Saint Kitts and Nevis'),
       ('LC', 'Saint Lucia'),
       ('VC', 'Saint Vincent and the Grenadines'),
       ('WS', 'Samoa'),
       ('SM', 'San Marino'),
       ('ST', 'Sao Tome and Principe'),
       ('SA', 'Saudi Arabia'),
       ('SN', 'Senegal'),
       ('RS', 'Serbia'),
       ('SC', 'Seychelles'),
       ('SL', 'Sierra Leone'),
       ('SG', 'Singapore'),
       ('SK', 'Slovakia'),
       ('SI', 'Slovenia'),
       ('SB', 'Solomon Islands'),
       ('SO', 'Somalia'),
       ('ZA', 'South Africa'),
       ('GS', 'South Georgia South Sandwich Islands'),
       ('SS', 'South Sudan'),
       ('ES', 'Spain'),
       ('LK', 'Sri Lanka'),
       ('SH', 'St. Helena'),
       ('PM', 'St. Pierre and Miquelon'),
       ('SD', 'Sudan'),
       ('SR', 'Suriname'),
       ('SJ', 'Svalbard and Jan Mayen Islands'),
       ('SZ', 'Eswatini'),
       ('SE', 'Sweden'),
       ('CH', 'Switzerland'),
       ('SY', 'Syrian Arab Republic'),
       ('TW', 'Taiwan'),
       ('TJ', 'Tajikistan'),
       ('TZ', 'Tanzania, United Republic of'),
       ('TH', 'Thailand'),
       ('TG', 'Togo'),
       ('TK', 'Tokelau'),
       ('TO', 'Tonga'),
       ('TT', 'Trinidad and Tobago'),
       ('TN', 'Tunisia'),
       ('TR', 'Turkey'),
       ('TM', 'Turkmenistan'),
       ('TC', 'Turks and Caicos Islands'),
       ('TV', 'Tuvalu'),
       ('UG', 'Uganda'),
       ('UA', 'Ukraine'),
       ('AE', 'United Arab Emirates'),
       ('GB', 'United Kingdom'),
       ('US', 'United States'),
       ('UM', 'United States minor outlying islands'),
       ('UY', 'Uruguay'),
       ('UZ', 'Uzbekistan'),
       ('VU', 'Vanuatu'),
       ('VA', 'Vatican City State'),
       ('VE', 'Venezuela'),
       ('VN', 'Vietnam'),
       ('VG', 'Virgin Islands (British)'),
       ('VI', 'Virgin Islands (U.S.)'),
       ('WF', 'Wallis and Futuna Islands'),
       ('EH', 'Western Sahara'),
       ('YE', 'Yemen'),
       ('ZM', 'Zambia'),
       ('ZW', 'Zimbabwe');

-------------------------- Timezones -------------------------------

INSERT INTO "Timezone" ("countryId", "id", "gmtOffset")
VALUES ('AF', 'Asia/Kabul', 'UTC +04:30'),
       ('AL', 'Europe/Tirane', 'UTC +01:00'),
       ('DZ', 'Africa/Algiers', 'UTC +01:00'),
       ('AS', 'Pacific/Pago_Pago', 'UTC -11:00'),
       ('AD', 'Europe/Andorra', 'UTC +01:00'),
       ('AO', 'Africa/Luanda', 'UTC +01:00'),
       ('AI', 'America/Anguilla', 'UTC -04:00'),
       ('AQ', 'Antarctica/Casey', 'UTC +11:00'),
       ('AQ', 'Antarctica/Davis', 'UTC +07:00'),
       ('AQ', 'Antarctica/DumontDUrville', 'UTC +10:00'),
       ('AQ', 'Antarctica/Mawson', 'UTC +05:00'),
       ('AQ', 'Antarctica/McMurdo', 'UTC +13:00'),
       ('AQ', 'Antarctica/Palmer', 'UTC -03:00'),
       ('AQ', 'Antarctica/Rothera', 'UTC -03:00'),
       ('AQ', 'Antarctica/Syowa', 'UTC +03:00'),
       ('AQ', 'Antarctica/Troll', 'UTC'),
       ('AQ', 'Antarctica/Vostok', 'UTC +06:00'),
       ('AG', 'America/Antigua', 'UTC -04:00'),
       ('AR', 'America/Argentina/Buenos_Aires', 'UTC -03:00'),
       ('AR', 'America/Argentina/Catamarca', 'UTC -03:00'),
       ('AR', 'America/Argentina/Cordoba', 'UTC -03:00'),
       ('AR', 'America/Argentina/Jujuy', 'UTC -03:00'),
       ('AR', 'America/Argentina/La_Rioja', 'UTC -03:00'),
       ('AR', 'America/Argentina/Mendoza', 'UTC -03:00'),
       ('AR', 'America/Argentina/Rio_Gallegos', 'UTC -03:00'),
       ('AR', 'America/Argentina/Salta', 'UTC -03:00'),
       ('AR', 'America/Argentina/San_Juan', 'UTC -03:00'),
       ('AR', 'America/Argentina/San_Luis', 'UTC -03:00'),
       ('AR', 'America/Argentina/Tucuman', 'UTC -03:00'),
       ('AR', 'America/Argentina/Ushuaia', 'UTC -03:00'),
       ('AM', 'Asia/Yerevan', 'UTC +04:00'),
       ('AW', 'America/Aruba', 'UTC -04:00'),
       ('AU', 'Antarctica/Macquarie', 'UTC +11:00'),
       ('AU', 'Australia/Adelaide', 'UTC +10:30'),
       ('AU', 'Australia/Brisbane', 'UTC +10:00'),
       ('AU', 'Australia/Broken_Hill', 'UTC +10:30'),
       ('AU', 'Australia/Darwin', 'UTC +09:30'),
       ('AU', 'Australia/Eucla', 'UTC +08:45'),
       ('AU', 'Australia/Hobart', 'UTC +11:00'),
       ('AU', 'Australia/Lindeman', 'UTC +10:00'),
       ('AU', 'Australia/Lord_Howe', 'UTC +11:00'),
       ('AU', 'Australia/Melbourne', 'UTC +11:00'),
       ('AU', 'Australia/Perth', 'UTC +08:00'),
       ('AU', 'Australia/Sydney', 'UTC +11:00'),
       ('AT', 'Europe/Vienna', 'UTC +01:00'),
       ('AZ', 'Asia/Baku', 'UTC +04:00'),
       ('BS', 'America/Nassau', 'UTC -05:00'),
       ('BH', 'Asia/Bahrain', 'UTC +03:00'),
       ('BD', 'Asia/Dhaka', 'UTC +06:00'),
       ('BB', 'America/Barbados', 'UTC -04:00'),
       ('BY', 'Europe/Minsk', 'UTC +03:00'),
       ('BE', 'Europe/Brussels', 'UTC +01:00'),
       ('BZ', 'America/Belize', 'UTC -06:00'),
       ('BJ', 'Africa/Porto-Novo', 'UTC +01:00'),
       ('BM', 'Atlantic/Bermuda', 'UTC -04:00'),
       ('BT', 'Asia/Thimphu', 'UTC +06:00'),
       ('BO', 'America/La_Paz', 'UTC -04:00'),
       ('BQ', 'America/Kralendijk', 'UTC -04:00'),
       ('BA', 'Europe/Sarajevo', 'UTC +01:00'),
       ('BW', 'Africa/Gaborone', 'UTC +02:00'),
       ('BR', 'America/Araguaina', 'UTC -03:00'),
       ('BR', 'America/Bahia', 'UTC -03:00'),
       ('BR', 'America/Belem', 'UTC -03:00'),
       ('BR', 'America/Boa_Vista', 'UTC -04:00'),
       ('BR', 'America/Campo_Grande', 'UTC -04:00'),
       ('BR', 'America/Cuiaba', 'UTC -04:00'),
       ('BR', 'America/Eirunepe', 'UTC -05:00'),
       ('BR', 'America/Fortaleza', 'UTC -03:00'),
       ('BR', 'America/Maceio', 'UTC -03:00'),
       ('BR', 'America/Manaus', 'UTC -04:00'),
       ('BR', 'America/Noronha', 'UTC -02:00'),
       ('BR', 'America/Porto_Velho', 'UTC -04:00'),
       ('BR', 'America/Recife', 'UTC -03:00'),
       ('BR', 'America/Rio_Branco', 'UTC -05:00'),
       ('BR', 'America/Santarem', 'UTC -03:00'),
       ('BR', 'America/Sao_Paulo', 'UTC -03:00'),
       ('IO', 'Indian/Chagos', 'UTC +06:00'),
       ('BN', 'Asia/Brunei', 'UTC +08:00'),
       ('BG', 'Europe/Sofia', 'UTC +02:00'),
       ('BF', 'Africa/Ouagadougou', 'UTC'),
       ('BI', 'Africa/Bujumbura', 'UTC +02:00'),
       ('KH', 'Asia/Phnom_Penh', 'UTC +07:00'),
       ('CM', 'Africa/Douala', 'UTC +01:00'),
       ('CA', 'America/Atikokan', 'UTC -05:00'),
       ('CA', 'America/Blanc-Sablon', 'UTC -04:00'),
       ('CA', 'America/Cambridge_Bay', 'UTC -07:00'),
       ('CA', 'America/Creston', 'UTC -07:00'),
       ('CA', 'America/Dawson', 'UTC -07:00'),
       ('CA', 'America/Dawson_Creek', 'UTC -07:00'),
       ('CA', 'America/Edmonton', 'UTC -07:00'),
       ('CA', 'America/Fort_Nelson', 'UTC -07:00'),
       ('CA', 'America/Glace_Bay', 'UTC -04:00'),
       ('CA', 'America/Goose_Bay', 'UTC -04:00'),
       ('CA', 'America/Halifax', 'UTC -04:00'),
       ('CA', 'America/Inuvik', 'UTC -07:00'),
       ('CA', 'America/Iqaluit', 'UTC -05:00'),
       ('CA', 'America/Moncton', 'UTC -04:00'),
       ('CA', 'America/Rankin_Inlet', 'UTC -06:00'),
       ('CA', 'America/Regina', 'UTC -06:00'),
       ('CA', 'America/Resolute', 'UTC -06:00'),
       ('CA', 'America/St_Johns', 'UTC -03:30'),
       ('CA', 'America/Swift_Current', 'UTC -06:00'),
       ('CA', 'America/Toronto', 'UTC -05:00'),
       ('CA', 'America/Vancouver', 'UTC -08:00'),
       ('CA', 'America/Whitehorse', 'UTC -07:00'),
       ('CA', 'America/Winnipeg', 'UTC -06:00'),
       ('CA', 'America/Yellowknife', 'UTC -07:00'),
       ('CV', 'Atlantic/Cape_Verde', 'UTC -01:00'),
       ('KY', 'America/Cayman', 'UTC -05:00'),
       ('CF', 'Africa/Bangui', 'UTC +01:00'),
       ('TD', 'Africa/Ndjamena', 'UTC +01:00'),
       ('CL', 'America/Punta_Arenas', 'UTC -03:00'),
       ('CL', 'America/Santiago', 'UTC -03:00'),
       ('CL', 'Pacific/Easter', 'UTC -05:00'),
       ('CN', 'Asia/Shanghai', 'UTC +08:00'),
       ('CN', 'Asia/Urumqi', 'UTC +06:00'),
       ('CX', 'Indian/Christmas', 'UTC +07:00'),
       ('CC', 'Indian/Cocos', 'UTC +06:30'),
       ('CO', 'America/Bogota', 'UTC -05:00'),
       ('KM', 'Indian/Comoro', 'UTC +03:00'),
       ('CG', 'Africa/Brazzaville', 'UTC +01:00'),
       ('CD', 'Africa/Kinshasa', 'UTC +01:00'),
       ('CD', 'Africa/Lubumbashi', 'UTC +02:00'),
       ('CK', 'Pacific/Rarotonga', 'UTC -10:00'),
       ('CR', 'America/Costa_Rica', 'UTC -06:00'),
       ('HR', 'Europe/Zagreb', 'UTC +01:00'),
       ('CU', 'America/Havana', 'UTC -05:00'),
       ('CW', 'America/Curacao', 'UTC -04:00'),
       ('CY', 'Asia/Famagusta', 'UTC +02:00'),
       ('CY', 'Asia/Nicosia', 'UTC +02:00'),
       ('CZ', 'Europe/Prague', 'UTC +01:00'),
       ('CI', 'Africa/Abidjan', 'UTC'),
       ('DK', 'Europe/Copenhagen', 'UTC +01:00'),
       ('DJ', 'Africa/Djibouti', 'UTC +03:00'),
       ('DM', 'America/Dominica', 'UTC -04:00'),
       ('DO', 'America/Santo_Domingo', 'UTC -04:00'),
       ('EC', 'America/Guayaquil', 'UTC -05:00'),
       ('EC', 'Pacific/Galapagos', 'UTC -06:00'),
       ('EG', 'Africa/Cairo', 'UTC +02:00'),
       ('SV', 'America/El_Salvador', 'UTC -06:00'),
       ('GQ', 'Africa/Malabo', 'UTC +01:00'),
       ('ER', 'Africa/Asmara', 'UTC +03:00'),
       ('EE', 'Europe/Tallinn', 'UTC +02:00'),
       ('ET', 'Africa/Addis_Ababa', 'UTC +03:00'),
       ('FK', 'Atlantic/Stanley', 'UTC -03:00'),
       ('FO', 'Atlantic/Faroe', 'UTC'),
       ('FJ', 'Pacific/Fiji', 'UTC +12:00'),
       ('FI', 'Europe/Helsinki', 'UTC +02:00'),
       ('FR', 'Europe/Paris', 'UTC +01:00'),
       ('GF', 'America/Cayenne', 'UTC -03:00'),
       ('PF', 'Pacific/Gambier', 'UTC -09:00'),
       ('PF', 'Pacific/Marquesas', 'UTC -09:30'),
       ('PF', 'Pacific/Tahiti', 'UTC -10:00'),
       ('TF', 'Indian/Kerguelen', 'UTC +05:00'),
       ('GA', 'Africa/Libreville', 'UTC +01:00'),
       ('GM', 'Africa/Banjul', 'UTC'),
       ('GE', 'Asia/Tbilisi', 'UTC +04:00'),
       ('DE', 'Europe/Berlin', 'UTC +01:00'),
       ('DE', 'Europe/Busingen', 'UTC +01:00'),
       ('GH', 'Africa/Accra', 'UTC'),
       ('GI', 'Europe/Gibraltar', 'UTC +01:00'),
       ('GR', 'Europe/Athens', 'UTC +02:00'),
       ('GL', 'America/Danmarkshavn', 'UTC'),
       ('GL', 'America/Nuuk', 'UTC -03:00'),
       ('GL', 'America/Scoresbysund', 'UTC -01:00'),
       ('GL', 'America/Thule', 'UTC -04:00'),
       ('GD', 'America/Grenada', 'UTC -04:00'),
       ('GP', 'America/Guadeloupe', 'UTC -04:00'),
       ('GU', 'Pacific/Guam', 'UTC +10:00'),
       ('GT', 'America/Guatemala', 'UTC -06:00'),
       ('GG', 'Europe/Guernsey', 'UTC'),
       ('GN', 'Africa/Conakry', 'UTC'),
       ('GW', 'Africa/Bissau', 'UTC'),
       ('GY', 'America/Guyana', 'UTC -04:00'),
       ('HT', 'America/Port-au-Prince', 'UTC -05:00'),
       ('VA', 'Europe/Vatican', 'UTC +01:00'),
       ('HN', 'America/Tegucigalpa', 'UTC -06:00'),
       ('HK', 'Asia/Hong_Kong', 'UTC +08:00'),
       ('HU', 'Europe/Budapest', 'UTC +01:00'),
       ('IS', 'Atlantic/Reykjavik', 'UTC'),
       ('IN', 'Asia/Kolkata', 'UTC +05:30'),
       ('ID', 'Asia/Jakarta', 'UTC +07:00'),
       ('ID', 'Asia/Jayapura', 'UTC +09:00'),
       ('ID', 'Asia/Makassar', 'UTC +08:00'),
       ('ID', 'Asia/Pontianak', 'UTC +07:00'),
       ('IR', 'Asia/Tehran', 'UTC +03:30'),
       ('IQ', 'Asia/Baghdad', 'UTC +03:00'),
       ('IE', 'Europe/Dublin', 'UTC'),
       ('IM', 'Europe/Isle_of_Man', 'UTC'),
       ('IL', 'Asia/Jerusalem', 'UTC +02:00'),
       ('IT', 'Europe/Rome', 'UTC +01:00'),
       ('JM', 'America/Jamaica', 'UTC -05:00'),
       ('JP', 'Asia/Tokyo', 'UTC +09:00'),
       ('JE', 'Europe/Jersey', 'UTC'),
       ('JO', 'Asia/Amman', 'UTC +03:00'),
       ('KZ', 'Asia/Almaty', 'UTC +06:00'),
       ('KZ', 'Asia/Aqtau', 'UTC +05:00'),
       ('KZ', 'Asia/Aqtobe', 'UTC +05:00'),
       ('KZ', 'Asia/Atyrau', 'UTC +05:00'),
       ('KZ', 'Asia/Oral', 'UTC +05:00'),
       ('KZ', 'Asia/Qostanay', 'UTC +06:00'),
       ('KZ', 'Asia/Qyzylorda', 'UTC +05:00'),
       ('KE', 'Africa/Nairobi', 'UTC +03:00'),
       ('KI', 'Pacific/Kanton', 'UTC +13:00'),
       ('KI', 'Pacific/Kiritimati', 'UTC +14:00'),
       ('KI', 'Pacific/Tarawa', 'UTC +12:00'),
       ('KP', 'Asia/Pyongyang', 'UTC +09:00'),
       ('KR', 'Asia/Seoul', 'UTC +09:00'),
       ('KW', 'Asia/Kuwait', 'UTC +03:00'),
       ('KG', 'Asia/Bishkek', 'UTC +06:00'),
       ('LA', 'Asia/Vientiane', 'UTC +07:00'),
       ('LV', 'Europe/Riga', 'UTC +02:00'),
       ('LB', 'Asia/Beirut', 'UTC +02:00'),
       ('LS', 'Africa/Maseru', 'UTC +02:00'),
       ('LR', 'Africa/Monrovia', 'UTC'),
       ('LY', 'Africa/Tripoli', 'UTC +02:00'),
       ('LI', 'Europe/Vaduz', 'UTC +01:00'),
       ('LT', 'Europe/Vilnius', 'UTC +02:00'),
       ('LU', 'Europe/Luxembourg', 'UTC +01:00'),
       ('MO', 'Asia/Macau', 'UTC +08:00'),
       ('MK', 'Europe/Skopje', 'UTC +01:00'),
       ('MG', 'Indian/Antananarivo', 'UTC +03:00'),
       ('MW', 'Africa/Blantyre', 'UTC +02:00'),
       ('MY', 'Asia/Kuala_Lumpur', 'UTC +08:00'),
       ('MY', 'Asia/Kuching', 'UTC +08:00'),
       ('MV', 'Indian/Maldives', 'UTC +05:00'),
       ('ML', 'Africa/Bamako', 'UTC'),
       ('MT', 'Europe/Malta', 'UTC +01:00'),
       ('MH', 'Pacific/Kwajalein', 'UTC +12:00'),
       ('MH', 'Pacific/Majuro', 'UTC +12:00'),
       ('MQ', 'America/Martinique', 'UTC -04:00'),
       ('MR', 'Africa/Nouakchott', 'UTC'),
       ('MU', 'Indian/Mauritius', 'UTC +04:00'),
       ('YT', 'Indian/Mayotte', 'UTC +03:00'),
       ('MX', 'America/Bahia_Banderas', 'UTC -06:00'),
       ('MX', 'America/Cancun', 'UTC -05:00'),
       ('MX', 'America/Chihuahua', 'UTC -06:00'),
       ('MX', 'America/Ciudad_Juarez', 'UTC -07:00'),
       ('MX', 'America/Hermosillo', 'UTC -07:00'),
       ('MX', 'America/Matamoros', 'UTC -06:00'),
       ('MX', 'America/Mazatlan', 'UTC -07:00'),
       ('MX', 'America/Merida', 'UTC -06:00'),
       ('MX', 'America/Mexico_City', 'UTC -06:00'),
       ('MX', 'America/Monterrey', 'UTC -06:00'),
       ('MX', 'America/Ojinaga', 'UTC -06:00'),
       ('MX', 'America/Tijuana', 'UTC -08:00'),
       ('FM', 'Pacific/Chuuk', 'UTC +10:00'),
       ('FM', 'Pacific/Kosrae', 'UTC +11:00'),
       ('FM', 'Pacific/Pohnpei', 'UTC +11:00'),
       ('MD', 'Europe/Chisinau', 'UTC +02:00'),
       ('MC', 'Europe/Monaco', 'UTC +01:00'),
       ('MN', 'Asia/Choibalsan', 'UTC +08:00'),
       ('MN', 'Asia/Hovd', 'UTC +07:00'),
       ('MN', 'Asia/Ulaanbaatar', 'UTC +08:00'),
       ('ME', 'Europe/Podgorica', 'UTC +01:00'),
       ('MS', 'America/Montserrat', 'UTC -04:00'),
       ('MA', 'Africa/Casablanca', 'UTC +01:00'),
       ('MA', 'Africa/El_Aaiun', 'UTC +01:00'),
       ('MZ', 'Africa/Maputo', 'UTC +02:00'),
       ('MM', 'Asia/Yangon', 'UTC +06:30'),
       ('NA', 'Africa/Windhoek', 'UTC +02:00'),
       ('NR', 'Pacific/Nauru', 'UTC +12:00'),
       ('NP', 'Asia/Kathmandu', 'UTC +05:45'),
       ('NL', 'Europe/Amsterdam', 'UTC +01:00'),
       ('NC', 'Pacific/Noumea', 'UTC +11:00'),
       ('NZ', 'Pacific/Auckland', 'UTC +13:00'),
       ('NZ', 'Pacific/Chatham', 'UTC +13:45'),
       ('NI', 'America/Managua', 'UTC -06:00'),
       ('NE', 'Africa/Niamey', 'UTC +01:00'),
       ('NG', 'Africa/Lagos', 'UTC +01:00'),
       ('NU', 'Pacific/Niue', 'UTC -11:00'),
       ('NF', 'Pacific/Norfolk', 'UTC +12:00'),
       ('MP', 'Pacific/Saipan', 'UTC +10:00'),
       ('NO', 'Europe/Oslo', 'UTC +01:00'),
       ('OM', 'Asia/Muscat', 'UTC +04:00'),
       ('PK', 'Asia/Karachi', 'UTC +05:00'),
       ('PW', 'Pacific/Palau', 'UTC +09:00'),
       ('PS', 'Asia/Gaza', 'UTC +02:00'),
       ('PS', 'Asia/Hebron', 'UTC +02:00'),
       ('PA', 'America/Panama', 'UTC -05:00'),
       ('PG', 'Pacific/Bougainville', 'UTC +11:00'),
       ('PG', 'Pacific/Port_Moresby', 'UTC +10:00'),
       ('PY', 'America/Asuncion', 'UTC -03:00'),
       ('PE', 'America/Lima', 'UTC -05:00'),
       ('PH', 'Asia/Manila', 'UTC +08:00'),
       ('PN', 'Pacific/Pitcairn', 'UTC -08:00'),
       ('PL', 'Europe/Warsaw', 'UTC +01:00'),
       ('PT', 'Atlantic/Azores', 'UTC -01:00'),
       ('PT', 'Atlantic/Madeira', 'UTC'),
       ('PT', 'Europe/Lisbon', 'UTC'),
       ('PR', 'America/Puerto_Rico', 'UTC -04:00'),
       ('QA', 'Asia/Qatar', 'UTC +03:00'),
       ('RO', 'Europe/Bucharest', 'UTC +02:00'),
       ('RU', 'Asia/Anadyr', 'UTC +12:00'),
       ('RU', 'Asia/Barnaul', 'UTC +07:00'),
       ('RU', 'Asia/Chita', 'UTC +09:00'),
       ('RU', 'Asia/Irkutsk', 'UTC +08:00'),
       ('RU', 'Asia/Kamchatka', 'UTC +12:00'),
       ('RU', 'Asia/Khandyga', 'UTC +09:00'),
       ('RU', 'Asia/Krasnoyarsk', 'UTC +07:00'),
       ('RU', 'Asia/Magadan', 'UTC +11:00'),
       ('RU', 'Asia/Novokuznetsk', 'UTC +07:00'),
       ('RU', 'Asia/Novosibirsk', 'UTC +07:00'),
       ('RU', 'Asia/Omsk', 'UTC +06:00'),
       ('RU', 'Asia/Sakhalin', 'UTC +11:00'),
       ('RU', 'Asia/Srednekolymsk', 'UTC +11:00'),
       ('RU', 'Asia/Tomsk', 'UTC +07:00'),
       ('RU', 'Asia/Ust-Nera', 'UTC +10:00'),
       ('RU', 'Asia/Vladivostok', 'UTC +10:00'),
       ('RU', 'Asia/Yakutsk', 'UTC +09:00'),
       ('RU', 'Asia/Yekaterinburg', 'UTC +05:00'),
       ('RU', 'Europe/Astrakhan', 'UTC +04:00'),
       ('RU', 'Europe/Kaliningrad', 'UTC +02:00'),
       ('RU', 'Europe/Kirov', 'UTC +03:00'),
       ('RU', 'Europe/Moscow', 'UTC +03:00'),
       ('RU', 'Europe/Samara', 'UTC +04:00'),
       ('RU', 'Europe/Saratov', 'UTC +04:00'),
       ('RU', 'Europe/Ulyanovsk', 'UTC +04:00'),
       ('RU', 'Europe/Volgograd', 'UTC +03:00'),
       ('RW', 'Africa/Kigali', 'UTC +02:00'),
       ('RE', 'Indian/Reunion', 'UTC +04:00'),
       ('BL', 'America/St_Barthelemy', 'UTC -04:00'),
       ('SH', 'Atlantic/St_Helena', 'UTC'),
       ('KN', 'America/St_Kitts', 'UTC -04:00'),
       ('LC', 'America/St_Lucia', 'UTC -04:00'),
       ('MF', 'America/Marigot', 'UTC -04:00'),
       ('PM', 'America/Miquelon', 'UTC -03:00'),
       ('VC', 'America/St_Vincent', 'UTC -04:00'),
       ('WS', 'Pacific/Apia', 'UTC +13:00'),
       ('SM', 'Europe/San_Marino', 'UTC +01:00'),
       ('ST', 'Africa/Sao_Tome', 'UTC'),
       ('SA', 'Asia/Riyadh', 'UTC +03:00'),
       ('SN', 'Africa/Dakar', 'UTC'),
       ('RS', 'Europe/Belgrade', 'UTC +01:00'),
       ('SC', 'Indian/Mahe', 'UTC +04:00'),
       ('SL', 'Africa/Freetown', 'UTC'),
       ('SG', 'Asia/Singapore', 'UTC +08:00'),
       ('SX', 'America/Lower_Princes', 'UTC -04:00'),
       ('SK', 'Europe/Bratislava', 'UTC +01:00'),
       ('SI', 'Europe/Ljubljana', 'UTC +01:00'),
       ('SB', 'Pacific/Guadalcanal', 'UTC +11:00'),
       ('SO', 'Africa/Mogadishu', 'UTC +03:00'),
       ('ZA', 'Africa/Johannesburg', 'UTC +02:00'),
       ('GS', 'Atlantic/South_Georgia', 'UTC -02:00'),
       ('SS', 'Africa/Juba', 'UTC +02:00'),
       ('ES', 'Africa/Ceuta', 'UTC +01:00'),
       ('ES', 'Atlantic/Canary', 'UTC'),
       ('ES', 'Europe/Madrid', 'UTC +01:00'),
       ('LK', 'Asia/Colombo', 'UTC +05:30'),
       ('SD', 'Africa/Khartoum', 'UTC +02:00'),
       ('SR', 'America/Paramaribo', 'UTC -03:00'),
       ('SJ', 'Arctic/Longyearbyen', 'UTC +01:00'),
       ('SZ', 'Africa/Mbabane', 'UTC +02:00'),
       ('SE', 'Europe/Stockholm', 'UTC +01:00'),
       ('CH', 'Europe/Zurich', 'UTC +01:00'),
       ('SY', 'Asia/Damascus', 'UTC +03:00'),
       ('TW', 'Asia/Taipei', 'UTC +08:00'),
       ('TJ', 'Asia/Dushanbe', 'UTC +05:00'),
       ('TZ', 'Africa/Dar_es_Salaam', 'UTC +03:00'),
       ('TH', 'Asia/Bangkok', 'UTC +07:00'),
       ('TL', 'Asia/Dili', 'UTC +09:00'),
       ('TG', 'Africa/Lome', 'UTC'),
       ('TK', 'Pacific/Fakaofo', 'UTC +13:00'),
       ('TO', 'Pacific/Tongatapu', 'UTC +13:00'),
       ('TT', 'America/Port_of_Spain', 'UTC -04:00'),
       ('TN', 'Africa/Tunis', 'UTC +01:00'),
       ('TR', 'Europe/Istanbul', 'UTC +03:00'),
       ('TM', 'Asia/Ashgabat', 'UTC +05:00'),
       ('TC', 'America/Grand_Turk', 'UTC -05:00'),
       ('TV', 'Pacific/Funafuti', 'UTC +12:00'),
       ('UG', 'Africa/Kampala', 'UTC +03:00'),
       ('UA', 'Europe/Kyiv', 'UTC +02:00'),
       ('UA', 'Europe/Simferopol', 'UTC +03:00'),
       ('AE', 'Asia/Dubai', 'UTC +04:00'),
       ('GB', 'Europe/London', 'UTC'),
       ('US', 'America/Adak', 'UTC -10:00'),
       ('US', 'America/Anchorage', 'UTC -09:00'),
       ('US', 'America/Boise', 'UTC -07:00'),
       ('US', 'America/Chicago', 'UTC -06:00'),
       ('US', 'America/Denver', 'UTC -07:00'),
       ('US', 'America/Detroit', 'UTC -05:00'),
       ('US', 'America/Indiana/Indianapolis', 'UTC -05:00'),
       ('US', 'America/Indiana/Knox', 'UTC -06:00'),
       ('US', 'America/Indiana/Marengo', 'UTC -05:00'),
       ('US', 'America/Indiana/Petersburg', 'UTC -05:00'),
       ('US', 'America/Indiana/Tell_City', 'UTC -06:00'),
       ('US', 'America/Indiana/Vevay', 'UTC -05:00'),
       ('US', 'America/Indiana/Vincennes', 'UTC -05:00'),
       ('US', 'America/Indiana/Winamac', 'UTC -05:00'),
       ('US', 'America/Juneau', 'UTC -09:00'),
       ('US', 'America/Kentucky/Louisville', 'UTC -05:00'),
       ('US', 'America/Kentucky/Monticello', 'UTC -05:00'),
       ('US', 'America/Los_Angeles', 'UTC -08:00'),
       ('US', 'America/Menominee', 'UTC -06:00'),
       ('US', 'America/Metlakatla', 'UTC -09:00'),
       ('US', 'America/New_York', 'UTC -05:00'),
       ('US', 'America/Nome', 'UTC -09:00'),
       ('US', 'America/North_Dakota/Beulah', 'UTC -06:00'),
       ('US', 'America/North_Dakota/Center', 'UTC -06:00'),
       ('US', 'America/North_Dakota/New_Salem', 'UTC -06:00'),
       ('US', 'America/Phoenix', 'UTC -07:00'),
       ('US', 'America/Sitka', 'UTC -09:00'),
       ('US', 'America/Yakutat', 'UTC -09:00'),
       ('US', 'Pacific/Honolulu', 'UTC -10:00'),
       ('UM', 'Pacific/Midway', 'UTC -11:00'),
       ('UM', 'Pacific/Wake', 'UTC +12:00'),
       ('UY', 'America/Montevideo', 'UTC -03:00'),
       ('UZ', 'Asia/Samarkand', 'UTC +05:00'),
       ('UZ', 'Asia/Tashkent', 'UTC +05:00'),
       ('VU', 'Pacific/Efate', 'UTC +11:00'),
       ('VE', 'America/Caracas', 'UTC -04:00'),
       ('VN', 'Asia/Ho_Chi_Minh', 'UTC +07:00'),
       ('VG', 'America/Tortola', 'UTC -04:00'),
       ('VI', 'America/St_Thomas', 'UTC -04:00'),
       ('WF', 'Pacific/Wallis', 'UTC +12:00'),
       ('YE', 'Asia/Aden', 'UTC +03:00'),
       ('ZM', 'Africa/Lusaka', 'UTC +02:00'),
       ('ZW', 'Africa/Harare', 'UTC +02:00'),
       ('AX', 'Europe/Mariehamn', 'UTC +02:00');
