-- CreateEnum
CREATE TYPE "EmailTemplateName" AS ENUM ('CLAIM_REQUEST_EMAIL_FOR_ADMIN', 'CLAIM_REQUEST_EMAIL_FOR_CUSTOMER', 'CLAIM_REFUND_EMAIL_FOR_CUSTOMER', 'CLAIM_REORDER_EMAIL_FOR_CUSTOMER', 'CLAIM_CANCEL_EMAIL_FOR_CUSTOMER');

-- AlterTable
ALTER TABLE "EmailTemplate" ADD COLUMN     "name" "EmailTemplateName";

-- AlterTable
ALTER TABLE "PackageProtection" ALTER COLUMN "percentage" SET DEFAULT 0,
ALTER COLUMN "icon" SET DEFAULT 'three';
